name: Publish Docker image

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'


jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat docker/VERSION)"

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/coltoneshaw/${{ github.repository }}/mm-health-pandoc:${{ steps.get_version.outputs.VERSION }} .
          docker push ghcr.io/coltoneshaw/${{ github.repository }}/mm-health-pandoc:${{ steps.get_version.outputs.VERSION }}